events {}

http {
  server {
    listen 443 ssl;
    server_name davx.infra.1995parham.me;

    ssl_certificate     /etc/nginx/ssl/davx.infra.1995parham.me/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/davx.infra.1995parham.me/key.pem;

    # RFC 6764 service discovery
    location = /.well-known/caldav {
      return 307 $scheme://$host/user/calendars/;
    }
    location = /.well-known/carddav {
      return 307 $scheme://$host/user/contacts/;
    }

    location / {
      auth_basic "Xandikos";
      auth_basic_user_file /etc/nginx/htpasswd;

      proxy_pass http://xandikos:8000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_buffering off;
    }
  }
}
